### ISSUE TITLE
Markdown header gets indented after list

### ISSUE THREAD

**Issue by hyperknot** [prettier/prettier#12677]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBWAdARgAQCpcDKcYMAltNpvgDpS0C02AhgA4sA2cD2ARk1PybcwACzgAncQE9atDACY8hYmQryadKAHURU7KQDO2GCMPYDK8lH1R2pKHAAmAflmbaIADQgILVVANkUCZJCAB3AAUQhECUJnYwpilA7x5xJjAAazgYAiYAWzgAGXs4ZAAzeItU9KycghYM+wBzZBhxAFc4bzh8nidHJyL+Zo6mZrgAMQhxfKYYMihWuI6YCC8QERh89h1SeANGsDgiAP3SADd9qWRwAxSQewtxGAj05rmKqu6QACsDAAeBBanAAih0IPAvuxqiBGuJnrc5uJMo5wlANixxPYYFpSI4TMgABwABm8WIgFi06RYtyxcGeFzK3gAjhD4G9fLEQEwDPQHE4nBtxHA2aQRW9xp8kJUYT8LPlSG1OvKQXBwZCyjLvt4YEweHiCSJkPJdelSHYlgBhCD5aUgBmoDYdCwAFX1sVlsIuXQAklBBrACGBsX4AIIBggwKScaEWAC+8aAA)

```sh
--parser markdown
```

**Input:**

```markdown
5.1 **Section 1**

- apple
- banana
- cherry

5.2 **Section 2**

Why is this section indented?




```

**Output:**

```markdown
5.1 **Section 1**

- apple
- banana
- cherry

  5.2 **Section 2**

Why is this section indented?

```

**Expected behavior:**
The second section shouldn't be indented.

**Comment by kachkaev** [comment]
Interestingly, this only happens when a line starts with `\d+\.\S`:

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAGwJYGcYA6URALOhANZFEY77VQkBM5VxUteh7zAdKw070eTXgAZ0AMwCG2TIKxcGfZlNnz2Q7qVEANNXIV1tjPQE0AWgY01FworxUtKRpewCCj521vGG7gEYvAU07EwDPVRcoEAAaEAgABxhsaFxkUGkAJyyIAHcABWyEdJRpTDzpAE90+IAjLOkwCjgYAGVpAFs4ABlsKDhkGUxcOHrG5ta2xKb+gHNkGCyAVzGQOE66uAATbZ2e6Sg55ek5uAAxCCzO6RgUo+QQaWWYCDiQAAsYTswAdQ-sPBcDMwHA2iVAdgAG6AqqPMC4WogfqjLIwAqNOY3IblUbxABWuAAHm15pg4ABFZYQeA4kZrGZZVGPG5ZCjbfIxeKJLL9GC-bDbGAfZAADjE3Nyo1+jUSjx5cFRUMG8QAjtT4BikqUnrhUAMdjt3lk4OrsCaMadsUhhniQKNOthFis1rgyZSNYMbbi1jBpHUBUKRUgmPElup5gBhCCda3rXAAVney1GABV-aVbWsoasAJJQPawNpgXnJdwFtowKrkumjAC+daAA)

```sh
--parser markdown
```

**Input:**

```markdown
- list

4 ok

- list

42 ok

- list

42. ok

- list

42.0 fail

- list

42.42 fail

- list

42.X fail

- list

42.XYZ fail

- list

.42.42 ok

- list

A.42 ok

- list

A1.42 ok

- list

1A.42 ok

```

**Output:**

```markdown
- list

4 ok

- list

42 ok

- list

42. ok

- list

  42.0 fail

- list

  42.42 fail

- list

  42.X fail

- list

  42.XYZ fail

- list

.42.42 ok

- list

A.42 ok

- list

A1.42 ok

- list

1A.42 ok

```

**Comment by fisker** [comment]
This may already fixed in remark-parser, but we are using a old version.

**Comment by seiyab** [comment]
https://github.com/prettier/prettier/pull/18277 fixes it.

**Comment by kachkaev** [comment]
@seiyab can you please elaborate? Still seeing this:

**Prettier v3.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBWAdARgAQCpcDKcYMAltNpvgDpS0C02AhgA4sA2cD2ARk1PybcwACzgAncQE9atDACY8hYmQryadKAHURU7KQDO2GCMPYDK8lH1R2pKHAAmAflmbaIADQgILVVANkUCZJCAB3AAUQhECUJnYwpilA7x5xJjAAazgYAiYAWzgAGXs4ZAAzeItU9KycghYM+wBzZBhxAFc4bzh8nidHJyL+Zo6mZrgAMQhxfKYYMihWuI6YCC8QERh89h1SeANGsDgiAP3SADd9qWRwAxSQewtxGAj05rmKqu6QACsDAAeBBanAAih0IPAvuxqiBGuJnrc5uJMo5wlANixxPYYFpSI4TMgABwABm8WIgFi06RYtyxcGeFzK3gAjhD4G9fLEQEwDPQHE4nBtxHA2aQRW9xp8kJUYT8LPlSG1OvKQXBwZCyjLvt4YEweHiCSJkPJdelSHYlgBhCD5aUgBmoDYdCwAFX1sVlsIuXQAklBBrACGBsX4AIIBggwKScaEWAC+8aAA)

```sh
--parser markdown
--trailing-comma es5
```

**Input:**

```markdown
5.1 **Section 1**

- apple
- banana
- cherry

5.2 **Section 2**

Why is this section inlined?




```

**Output:**

```markdown
5.1 **Section 1**

- apple
- banana
- cherry

  5.2 **Section 2**

Why is this section inlined?

```

**Comment by seiyab** [comment]
Ah, sorry, I missed to mention that it's not released yet.
You can confirm the fix switching to `next` version in playground
