### ISSUE TITLE
Support .prettierrc.js when type module is used in package.json

### ISSUE THREAD

**Issue by git-chrisp** [prettier/prettier#12701]
When using pnpm, one has to use require.resolve or import.meta.resolve in the .prettierrc.js configuration to resolve plugins. As I have type set to module in my package.json, .prettierrc.js throws an error.

**Environments:**

- Prettier Version: 2.6.2
- Running Prettier via: CLI
- Runtime: VS Code Linux
- Operating System: Ubuntu
- Prettier plugins (if any): prettier-plugin-import-sort

**Steps to reproduce:**

1. Set "type": "module" in package.json
2. Create a .prettierrc.js:

```javascript
const config = {
  tabWidth: 2,
  plugins: [
    import.meta.resolve('prettier-plugin-import-sort')
  ]
}

export default config
```

**Expected behavior:**

Should work.

**Actual behavior:**

`Error [ERR_REQUIRE_ESM]: require() of ES Module /home/dev/project/.prettierrc.js from /home/dev/.vscode/extensions/esbenp.prettier-vscode-9.5.0/node_modules/prettier/third-party.js not supported.
.prettierrc.js is treated as an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which declares all .js files in that package scope as ES modules.
Instead rename .prettierrc.js to end in .cjs, change the requiring code to use dynamic import() which is available in all CommonJS modules, or change "type": "module" to "type": "commonjs" in /home/dev/project/package.json to treat all .js files as CommonJS (using .mjs for all ES modules instead).`

**Comment by fisker** [comment]
This can't be done before we fix https://github.com/prettier/prettier/issues/4459. After we merge https://github.com/prettier/prettier/pull/12574, we'll be able to implement this.

**Comment by fisker** [comment]
Fixed in #13130

**Comment by sirrobert** [comment]
For me this happens because prettier updates `.eslintrc.js.`  Adding `.eslintrc.js` to `.prettierignore` doesn't work for some reason.  My workaround is to change my formatting script in `package.json` to look like this:

```
"scripts": {
   ...
  "format": "prettier --plugin-search-dir . --write .; git checkout .eslintrc.js"
},
```

It's super dirty, but it works for now.  I'm just letting prettier mangle the `.eslintrc.js`, then checking it back out of source control.

**Comment by domnantas** [comment]
I am using prettier 3.0.0 and I'm still getting this error with `prettier.config.js` and `export default {...}`
