### ISSUE TITLE
Prettier incorrectly formats an IIFE with JSDoc

### ISSUE THREAD

**Issue by WillsterJohnson** [prettier/prettier#12967]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAOlA9AKh5gAhwIAEAHAQwCcKBbA4KAV1oCM4qBfAiw486nQbM2Hbqz5ZMqCgBoCrAJQEAvAD4GhApCgBnCABs4AOgMQA5jIIBqBYoDcmTpkWpFmELJAQyMAJbQusig1FQQAO4ACtQIQSgUBuEUAJ5BXqw0YADWcDAAynRwADJ+UHDIAGYJunDpmTn5lGCl5sgwVEy1IHCiACa9cL1FFFDmTBTmcABiEFS0FDD+o8ggFEwwEJ4gABYwtAYA6tt+8LpNcHmxJ34AbifJK2C6aSClNVQwkTTm85XVXQArXQADzyLSMAEUmBB4H8DDUvJQqO8VqwKOwDFsyFRSjADn5ejBtsgABwABkRYRqBxoZBW2Lg7xu5S8AEdofAvj44qtdABaMqDQZbKhwdl+UVfCa-JBVeFdGq0PxtDoK8FwKEw8qy-5eGDo-GE4lIABMepofgMLQAwhBaDLuroAKxbJg1AAq6LicoRIBunQAklABrA8mAcb4AILBvIwZJGOE1TicIA)

```sh
--parser babel
```

**Input:**

```jsx
(
/**
 * @param {number} a
 * @param {number} b
 */
(a, b) => { // <-- in editor hints apply the types to a and b
  console.log(a + b);
}
)()

```

**Output:**

```jsx
/**
 * @param {number} a
 * @param {number} b
 */
((a, b) => { // <-- in editor hints believe that a and b are of type `any` (the types have been formatted away)
  console.log(a + b);
})();

```

**Expected behavior:**

Prettier should not format code in such a way that functionality is broken, even if that functionality is not strictly functionality of JavaScript itself; editors inferring information from your code is still functionality of your code.

I'm aware that an IIFE with arguments isn't common, but neither are any other edge cases. I strongly prefer the IIFE model over declaring a `main` function and calling it later, however this problem with the formatter has forced me to use *syntax* I dislike, not just formatting I don't agree with.

Obviously this isn't anyones fault - nobody's out to get the IIFE users - it's just very frustrating for me having to use an alternative I'd prefer not to use. Apologies if I seem a bit grouchy here, I mean no harm. 

**Importance:** nice to have

**Comment by zsakowitz** [comment]
@willster277 I know this isn't a solution to the Prettier problem, but you can use `@type` tags on each parameter like so:

```javascript
((/** @type {number} */ a, /** @type {number} */ b) => {
  console.log(a + b);
})();
```

**Comment by alexander-akait** [comment]
Yep, bug, there are around 3 issues about this, duplicate

**Comment by willster277** [comment]
apologies, I couldn't find related issues. I looked at everything that came up when searching "jsdoc" or "iife" and I don't recall seeing this.

Is there a "main" (or at least first) issue about this we can link to and close this one?

**Comment by NirvanaPhX** [comment]
I am having a similar issue with IIFE. I saw the first issue was in April 2021 but still haven't been solved with the latest version. Hope this can be fixed soon. Thanks.
Also, if someone has a work around please post.

**Comment by sebiniemann** [comment]
Hi everyone, we're also experiencing this issue.

I believe the issue @NirvanaPhX mentioned is #5850. However, it's currently locked for further comments and marked as fixed by #10222.

Despite this, in the current version of Prettier, the isolated minimal example provided by @thorn0 (which was mentioned in #5850) still results in the same JSDoc/TypeScript-incompatible output: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTACgB0pNMB6AKiswAEAHbAJ2wFtNgqBfTAI0xUKpcoT4BKfAD5O3UuMLiQAGhAQGMAJbpkoFswgB3AAosEaZCGwAbQ9gCeF1X1ZgA1nBgBldnAAymlBwyABmNmhwqhB8AFZwYDAA6qwMlgzMcBHMAG7Bzq4e3kxggQDmyDDMAK6RIBFsmhXVtXAAHgxwzJpsCDA2APIdrDAQzMYQaJpa0JYIACYqIG1D3b02ACqdUCyamaHhtZNQpdZwAIpVEPD71hGqMWitXmWnF1fBSGG3tQCOl-DGAwMCwobBoAC0QTgc2hi0q2E01jKAGEIGw2NhLDZrIsjic4ABBGCVTR8KoAzoBII3O4gAAWMDY1kSdKmmWKcC85immmyU3sljAaCcIGyNQAklAYbAvGAuhoCVKvDB7KcabV0hM4MlsKkUOlMp1cotAlkYIDsKUMerVExmFlLHxsHw4DjbV1YIlNHMYHTkAAOAAMqgyf00GQtVsxnwOqj6fC9Pr9SAATKoqhF1s6QV9aXA2C65jC5n5sMcqpa4AAxUYY4llLHkiAgbjcIA

**Comment by WillsterJohnson** [comment]
Wow, completely forgot about this.

Can confirm it's still an issue. It seems that prettier is taking the comment and making it part of the previous statement;

**Input:**

```js
labelsGetTooMuchHate: {}
(
/**
 * @param {number} a
 * @param {number} b
 */
(a, b) => {
  console.log(a + b);
}
)()
```

**Output:**

```js
labelsGetTooMuchHate: {
} /**
  * @param {number} a
  * @param {number} b
  */
;((a, b) => {
  console.log(a + b)
})()
```


**Output (with my own newlines & whitespace):**

```js
labelsGetTooMuchHate: {
} /**
  * @param {number} a
  * @param {number} b
  */

;

((a, b) => {
  console.log(a + b)
})()
```

Notice the semicolon which has been added to prevent the code being interpreted as a call expression where the callee is `labelsGetTooMuchHate: {}`. The comment has been placed on the wrong side of that semicolon.

---

A similar issue arises in typescript where `@ts-ignore` and `@ts-expect-error` get moved to the wrong place. Imagine in the following example that instead of a very long identifier there's a multiline expression which cant collapse into `for (...) <expr>`;

**Input:**

```ts
for (const foo of bar)
  // @ts-expect-error
  foo.someReallyLongNameToPreventCollapsingThisForLoopIntoOneLine_OhManWhyIsMyPrintWidthSoDamnHigh()
```

**Output:**

```ts
// @ts-expect-error
for (const foo of bar)
  foo.someReallyLongNameToPreventCollapsingThisForLoopIntoOneLine_OhManWhyIsMyPrintWidthSoDamnHigh()
```

Now prettier has caused my code to error, as the `@ts-expect-error` comment is pointing in the wrong place.

---

It seems that, generally speaking, prettier doesn't know how to correctly deal with comments and just guesses.
