### ISSUE TITLE
End of multiline ternary expressions not aligned with colon anymore when using tab indentation

### ISSUE THREAD

**Issue by paescuj** [prettier/prettier#15783]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0AmBLGHoAID8ucAHgA4BOAkgGYAq5ArnLkrsADpS5FlXUBiAQwA2AZzicAvgG4QAGhARS2aKOShB5chADuABU0I1KETsEBPNQoBG5QWADWcGAGVBAWzgAZDFDjJqEXEbO0dnF1J7XwBzZBhGOAVxdww4hIUSUjhyDE9YEVpsqE0MOGNAsUSQURjhOABFBgh4AKCqgCtRYhdahqaWpArgkABHfrg9bVJjEEFRAFo-ODRl+RB4wQxhGIBhCHd3QWRZ4WE1mqhouoBBGHiMawZ4PWyfP1bKhQALGHdhAHUvlgypEwHAXEYsBgAG5YczHMCiKwgaFMShQFawFxgHLKa4Ylwwcx1D7DCgQcT-OykY4UMrZaH+BS+cTkGCTQTRQ6kqqRcis47WQTWOBnBQUXwwf4YNAwL7IAAcAAYFOQ4GMMGqOVyjoM2goYMLpbL5UgAEwKBjiWjC4zxJgZdwitArNBeQSXBicuD8CDkQ53GLHQRPCAgSSSIA)

```sh
--parser babel
--use-tabs
```

**Input:**

```jsx
condition ? exprIfTrue : {
  exprIfFalse
};
```

**Output:**

Ends with a hard tab and is not aligned with the colon anymore (same goes for truthy expression):

```jsx
condition
	? exprIfTrue
	: {
			exprIfFalse,
		};

```

**Expected behavior:**

Should end with a soft indent to be aligned with colon, as before with `prettier@3.1.0`:

```jsx
condition
	? exprIfTrue
	: {
			exprIfFalse,
	  };

```

Most likely related to https://github.com/prettier/prettier/pull/15662.

Thanks for your work ❤️

**Comment by ehoogeveen-medweb** [comment]
Note: There was an experimental change in https://github.com/prettier/prettier/pull/15662 that would have fixed this, but it went too far, also changing cases like
```
	condition ? exprIfTrue : exprIfFalse
```
to
```
	condition ?	exprIfTrue :	exprIfFalse
```
As I commented [there](https://github.com/prettier/prettier/pull/15662#discussion_r1399461148), I think it's only safe to use tabs after non-tab characters if it's after a single, tab-aligned character (like `?` or `:`).

**Comment by ehoogeveen-medweb** [comment]
Technically I guess it's impossible to be fully consistent using tabs, if you consider a tab width of 1 space:
```js
condition
 ? exprIfTrue
 : {
   exprIfFalse,
  };
```
But I doubt anyone actually uses a tab width of 1, and it works with a tab width of 2 and higher:
```js
condition
  ? exprIfTrue
  : {
      exprIfFalse,
    };
```

**Comment by sosukesuzuki** [comment]
This is fixed by #15662. Please wait next release

**Prettier pr-15662**
[Playground link](https://deploy-preview-15662--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0AmBLGHoAID8ucAHgA4BOAkgGYAq5ArnLkrsADpS5FlXUBiAQwA2AZzicAvgG4QAGhARS2aKOShB5chADuABU0I1KETsEBPNQoBG5QWADWcGAGVBAWzgAZDFDjJqEXEbO0dnF1J7XwBzZBhGOAVxdww4hKSY4TgARQYIeACgxJAAK1FiF0ycvIKkQLFigEcauD1tUmMQQVEAWj84NAH5EHjBDGEYgGEId3dBZC7hYWHRKoBBGHiMawZ4PThyHz9ChoUACxh3YQB1M6w4UUiwOBcjLAwANyxzBbBRKxAHyYlCgg1gLjA5AwyjWoJcMHMWROwRAFAg4mudlICwoDwOH38Cl84nIMDagmic2RxUi5BJC2sgmscGWCgovhg1wwaBgZ2QAA4AAwKchwZoYUXkynzOpFBQwJlcnl8pAAJgUDHEtCZxniTAUcHczLQgzQXkEUGiDApcH4EHIc02MQWgl2EBAkkkQA)

```sh
--parser babel
--use-tabs
```

**Input:**

```jsx
condition ? exprIfTrue : {
  exprIfFalse
};
```

**Output:**

```jsx
condition
	?	exprIfTrue
	:	{
			exprIfFalse,
		};

```

**Comment by ehoogeveen-medweb** [comment]
I'm confused, didn't that PR make it into Prettier v3.1.1, which this bug report is for? And I see the same output in both playgrounds:
```js
condition
	? exprIfTrue
	: {
			exprIfFalse,
		};
```

**Comment by paescuj** [comment]
@sosukesuzuki This is still an issue in v3.2.1, could you please reopen? 🙏

**Comment by kachkaev** [comment]
Thanks for flagging this @paescuj! I can still observe misaligned `{ }` in the playground:

**Prettier 3.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0AmBLGHoAID8ucAHgA4BOAkgGYAq5ArnLkrsADpS5FlXUBiAQwA2AZzicAvgG4QAGhARS2aKOShB5chADuABU0I1KETsEBPNQoBG5QWADWcGAGVBAWzgAZDFDjJqEXEbO0dnF1J7XwBzZBhGOAVxdww4hIUSUjhyDE9YEVpsqE0MOGNAsUSQURjhOABFBgh4AKCqgCtRYhdahqaWpArgkABHfrg9bVJjEEFRAFo-ODRl+RB4wQxhGIBhCHd3QWRZ4WE1mqhouoBBGHiMawZ4PWyfP1bKhQALGHdhAHUvlgypEwHAXEYsBgAG5YczHMCiKwgaFMShQFawFxgHLKa4Ylwwcx1D7DCgQcT-OykY4UMrZaH+BS+cTkGCTQTRQ6kqqRcis47WQTWOBnBQUXwwf4YNAwL7IAAcAAYFOQ4GMMGqOVyjoM2goYMLpbL5UgAEwKBjiWjC4zxJgZdwitArNBeQSXBicuD8CDkQ53GLHQRPCAgSSSIA)

```sh
--parser babel
--use-tabs
```

**Input:**

```jsx
condition ? exprIfTrue : {
  exprIfFalse
};
```

**Output:**

```jsx
condition
	? exprIfTrue
	: {
			exprIfFalse,
		};

```

Reopening for further investigation. Expected output:

```jsx
condition
	?	exprIfTrue
	:	{
			exprIfFalse,
		};
```

**Comment by sndrrth** [comment]
Why is the expected output with tabs instead of spaces after `?` and `:`? In previous versions Prettier used spaces which is much more readable imho even if it results in a mix of tabs and spaces (if tabs are enabled).

```
condition
	? exprIfTrue
	: {
		exprIfFalse,
	  };
```

**Comment by eamodio** [comment]
I really wish that #15662 was reverted, or at a minimum be able to turn it off -- it is what is causing us to have to stick on `3.1.0`.

`useTabs` shouldn't, imo, be interpreted to mean spaces can't be used anywhere -- since we still use spaces in TONS of places in code even if we indent with tabs. There is certainly a grey area since for the lines outside the `?` and `:` prefix are technically getting indented, but imo alignment with the `?` & `:` lines are more important than sticking with pure tabs (should still use tabs up until the point where more granular spacing is needed -- which I believe was the case). Forcing a full tab between the `?` & `:` and their conditions is extremely undesirable.

Can this be turned off, opt-out, or reverted?
