### ISSUE TITLE
eslint disable line comments get moved to the next line

### ISSUE THREAD

**Issue by Andarist** [prettier/prettier#1726]
It prevents eslint from working properly

Reproduced issue - https://prettier.github.io/prettier/#%7B%22content%22%3A%22function*%20saga()%20%7B%5Cn%5Ctwhile%20(true)%20%7B%7D%20%2F%2F%20eslint-disable-line%20no-constant-condition%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by luftywiranda13** [comment]
you can use `// eslint-disable-next-line`, put it before the line you want to ignore

**Comment by Andarist** [comment]
Yeah, I already fixed the issue in my code like this, but this still is a problem I think which should be tackled. Any comment is geting pushed to the next line, if we want to achieve comments being alone on the line it would make more sense to move the comment to the line before it was originally put, moving it after creates misleading output.

**Comment by luftywiranda13** [comment]
maybe due to the name of this package is `prettier`
and `prettier` thinks it's prettier than before 🤣

**Comment by vjeux** [comment]
Implementing https://github.com/prettier/prettier/issues/1356 would solve this issue. I'm still not 100% sure that we should though.

**Comment by Andarist** [comment]
How comes? I think most of the people use inline comments when they want to comment this exact line, keeping them at least before line (and not after) preserve better context for the reader

**Comment by lydell** [comment]
@vjeux As far as I understand, #1356 is about how empty blocks in loops are formatted. This issue is not really about empty blocks, though:

```js
function* saga() {
	while (true) { // eslint-disable-line no-constant-condition
      doSomething();
    }
}
```
```js
function* saga() {
  while (true) {
    // eslint-disable-line no-constant-condition
    doSomething();
  }
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22function*%20saga()%20%7B%5Cn%5Ctwhile%20(true)%20%7B%20%2F%2F%20eslint-disable-line%20no-constant-condition%5Cn%20%20%20%20%20%20doSomething()%3B%5Cn%20%20%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Sorry but we are not going to support this use case. Comments placement is really hard to get right and we don't have a way to encode this in the current architecture. You can use `ignore-next-line` to get you unblocked.
