### ISSUE TITLE
1.9: Trailing comma not adding in code blocks in markdown

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#3402]
**Prettier 1.9.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBidACAyhAtnDACzgEMATASygHMAdKegA2YCsBnetvOAMQFcoYGBWgBhEgBsJACnoYMAMwgQANHIwAjEgCc1UeUohbd6rvniEq1AEqkpATwAy0agEEoZABIkK2+3vkzOBhLGgBRCTY4AM1tUgBrADkIAHd6AEoAbiZmehAVEAgAB2FoNmRQHW1UgAUdBHKUEgA3CAoyfJASNhhkBUkogo1tEjB44Kwi0atkGG0+aJAyCDA+gcWqKO0YGpHqXBI1yMX2AA8AIRGxiZJ8Ryo4I8HCvhgi14AmJ8Wp7S3kEAHbTxZYpKCdIraKgwADq7RCyAAHAAGAqQiBRGEjIoAyFwLbNR4FOIARz4vjguxI+0OSH6xwKUVwFFm80WbCsEjgAEU+BB4N8CjASBo4WQEUgPkKRhQJFZRHgDgDJBJOnwogAVEWNelRAC+eqAA)
```sh
--parser markdown
--trailing-comma all
```

**Input:**
````markdown
### Some heading

```js
someFunctionCall(
  foo,
  bar,
  foobar,
  sometehingReallyLongAndHairy,
  somethingElse,
  breakNow,
);
```

````

**Output:**
````markdown
### Some heading

```js
someFunctionCall(
  foo,
  bar,
  foobar,
  sometehingReallyLongAndHairy,
  somethingElse,
  breakNow
);
```

````

**Expected behavior:**

Same as 1.8.2, namely adding trailing comma

**Comment by azz** [comment]
https://github.com/prettier/prettier/blob/e09359d2428bdac40c30cd6a82c92a627d1e1d05/src/multiparser.js#L32

I think it's using the wrong object here @lydell (should fall back to parent options)

**Comment by lipis** [comment]
What time to be alive... pretty printing the code that is inside a doc.. and care about dangling commas! I love it..

**Comment by SimenB** [comment]
I'm not sure if you're sarcastic or not, but there's a 200 line diff in jest solely because of this.

**Comment by lipis** [comment]
This feature is awesome! :)

**Comment by lydell** [comment]
@azz Sorry, I messed that up. Went through too quickly with the refactoring and relied too much on just checking if the tests pass...

**Comment by azz** [comment]
We had tests for JSON in markdown, but none for JS with trailing commas in markdown.

**Comment by duailibe** [comment]
Fixed in 1.9.1!

**Comment by Haroenv** [comment]
I'm still seeing (again?) this in 1.9.2 https://github.com/algolia/algolia-sitemap/pull/54/files, is that reported somewhere else before?

**Comment by duailibe** [comment]
@Haroenv I don't understand, your `.prettierrc` has `trailingComma: "es5"`. What were you expecting to happen?

I can't reproduce on the playground:

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBidACAyhAtnDACzgEMATASygHMAdKegA2YCsBnetvOAMQFcoYGBWgBhEgBsJACnoYMAMwgQANHIwAjEgCc1UeUohbd6rvniEq1AEqkpATwAy0agEEoZABIkK2+3vkzOBhLGgBRCTY4AM1tUgBrADkIAHd6AEoAbiZmehAVEAgAB2FoNmRQIu0qGAB1CjIQ5AAOAAYCmBINesbCZAAmArYrCTgART4IeGQFSSiO7R8JK1E8XBJkEEkJfJANRbB44KwikjArZBhtPmiQdgAPACEDo5gsEnxHKjgZudvT7RRbSbdbaeJkVJQXZRXAUS7XW58KIAFS65SQs0ityoQJgAAVFtR1r8sQU4gBHPi+OAEkhEjYYv4FKoQKK1RZFTZVOBAgBuPwKOm0qTxOgQ6K2vIgDV2ELAJPmWzYMAVtwgfBgRQ1-VVAF9dUA)
```sh
--parser markdown
--trailing-comma all
```

**Input:**
````markdown
### Some heading

```js
someFunctionCall(
  foo,
  bar,
  foobar,
  sometehingReallyLongAndHairy,
  somethingElse,
  breakNow
);
```

````

**Output:**
````markdown
### Some heading

```js
someFunctionCall(
  foo,
  bar,
  foobar,
  sometehingReallyLongAndHairy,
  somethingElse,
  breakNow,
);
```

````

**Comment by azz** [comment]
...That's very strange.

**Comment by duailibe** [comment]
@Haroenv I just cloned the repo, runned prettier and got this diff:

````diff
diff --git a/README.md b/README.md
index 22367d4..26da32e 100644
--- a/README.md
+++ b/README.md
@@ -43,7 +43,7 @@ Where `algoliaConfig` holds the setup for your index. Make sure that the API key
 const algoliaConfig = {
   appId: 'XXXXX',
   apiKey: 'xxxxxx', // make sure the key has "browse" capability
-  indexName: 'xxxxxx'
+  indexName: 'xxxxxx',
 };
 ```
 
@@ -62,8 +62,8 @@ function hitToParams({ objectID, modified, downloadsRatio }) {
     priority,
     alternates: {
       languages: ['fr', 'pt-BR', 'zh-Hans'],
-      hitToURL: lang => url({ lang, objectID })
-    }
+      hitToURL: lang => url({ lang, objectID }),
+    },
   };
 }
 ```
````

**Comment by Haroenv** [comment]
Thanks for replying, super odd, maybe I have the wrong blob setup?

**Comment by azz** [comment]
What does `yarn prettier --version` report?

**Comment by SimenB** [comment]
Did you remember to run `yarn` before pushing the formatting changes to the branch?

**Comment by Haroenv** [comment]
I might have forgotten that. I started on a clean clone and it does reformat. My bad 😄
