### ISSUE TITLE
Typescript types with tagged template literals (TSX) result in awkward formatting

### ISSUE THREAD

**Issue by inlightmedia** [prettier/prettier#5697]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMAJARkwF5MNCSA6YgSwDdMAeXe4gYQgC2AB2gIYABQBOEIWgB8AAwA6UJTABm0GAFo0zAF5wkmAEwMArHAEBuFWs2xtAdzjMA5gAsYxgCTAAFELSsgCU1HKYgcFoDBjSUG6YAPyY5gAMaZjG5BkhAL62qhpa2uoAhgLMBHi+wJBQGGWwMfAAHjBMzGhCBGV4AGJaDA4w-RVVeAV2MEQw8JK6QmVgzAm1UTJoYVQRG7IMBO5eyZgA5GkMaQAsVqdZmGn5hWqQBBCS60Gb2xFf+20wfhvSRTIp+PZbcLTNR-GJgMRwSTQmBqFIKTAsbq9GqYdREVqFTBE4kk0mYMqHNxQbTMeACNDGeGwRGEslsokAKwArhhmOo8Np6vBYIyEZJWeyyQDtBT3FBRczxcoimo1MZTqc8pgAAICEjMMqRARlVrOZjEGAeT7RH6RWEMKAQABCkjgZQA1uIIKssClzndGegYE0YDFsRAuR0AEauj0iH0MGNu93kfJCVphYDIka6AxGUxWZ4wPIqBTWEAAGhAMhgzHQyFAZUk0ic4ibCDQyBAZVY3uIlZAMeW7rgMGwSxWCWQMEkXLgVa8AgIAHUPLS4N1lnBsB3aWxaXgu2A0J2q6s0IiJJIym5jchygQL1WOWhWi7h6PsBU4AAZVZwe8KSfEAX1abBVjcIgAEUuQgeBAMfecQCWSQL0kLsozKKNCGgAcgh9ZdzUtZAAA40irL4L2Xa8hC7IIN0RVgAKrV0AEcuWYV0pBvO8kAfYCL0qadZyQvQEmg2D4L4oCkODKNCItDxkBMKsZzKKoIP4AReJAR0oGYkAeTgAAVLDO2kxC8jyIA)
```sh
--parser babylon
```

**Input:**
```jsx
const StyledH1 = styled.div<StyledComponentProps>`
	font-size: 2.5em;
	font-weight: ${(props) => (props.strong ? 500 : 100)};
	font-family: ${constants.text.displayFont.fontFamily};
	letter-spacing: ${(props) => (props.light ? '0.04em' : 0)};
	color: ${(props) => props.textColor};
	${(props) =>
		props.center
			? ` display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;`
			: ''} @media (max-width: ${(props) => (props.noBreakPoint ? '0' : constants.layout.breakpoint.break1)}px) {
		font-size: 2em;
	}
`;
```

**Output:**
```jsx
const StyledH1 =
  styled.div <
  StyledComponentProps >
  `
	font-size: 2.5em;
	font-weight: ${props => (props.strong ? 500 : 100)};
	font-family: ${constants.text.displayFont.fontFamily};
	letter-spacing: ${props => (props.light ? "0.04em" : 0)};
	color: ${props => props.textColor};
	${props =>
    props.center
      ? ` display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;`
      : ""} @media (max-width: ${props =>
    props.noBreakPoint ? "0" : constants.layout.breakpoint.break1}px) {
		font-size: 2em;
	}
`;

```

**Expected behavior:**

My issue is with the very first line where it multi-lines the angled brackets.

```
const StyledH1 = styled.div<StyledComponentProps>`
	font-size: 2.5em;
	font-weight: ${(props) => (props.strong ? 500 : 100)};
	font-family: ${constants.text.displayFont.fontFamily};
	letter-spacing: ${(props) => (props.light ? '0.04em' : 0)};
	color: ${(props) => props.textColor};
	${(props) =>
		props.center
			? ` display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;`
			: ''} @media (max-width: ${(props) => (props.noBreakPoint ? '0' : constants.layout.breakpoint.break1)}px) {
		font-size: 2em;
	}
`;
```

This happens in ts and tsx files.

**Comment by j-f1** [comment]
When run on the TypeScript parser, there’s a different error:

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMAJARkwF5MNCSA6YgSwDcAeXe4gYQgFsADtAQwACgCcIgtAD4ABgB0oimADNoMALRpmALzhJMAJgYBWOPwDcy1RthaA7nGYBzABYwjAEmAAKQSkZAEpqWUwAoLQGDCkoV0wAfkwzAAZUzCNydOCAXxsVdU0tNQBDfmYCPB9gSCgMUtho+AAPGCZmNEECUrwAMU0Gexg+8sq8fNsYIhh4CR1BUrBmeJrI6TRQqnD1mQYCN08kzAByVIZUgBZLE8zMVLyC1UgCCAk1wI2t8M+91pg+K8JJNCr5dpswlNVL9omBRHAJFCYKpkvJMCwuj1qpg1EQWgVMISicSSZhSgdXFAtMx4Pw0EY4bAEQTSazCQArACuGGYajwWjq8FgDPhEhZbNJ-y05LcUBFTLFSkKqlURhOJ1ymAAAvwSMxShF+KUWk5mMQYO4PlFvhEYQwoBAAEISOClADWYggKywyTOtwZ6BgjRg0SxEE57QARi73cJvQxo663eQ8oIWqFgEjhjp9IYTJYnjBcsp5FYQAAaEDSGDMdDIUClCRSRxiRsINDIEClVhe4gVkDRpZuuAwbCLZbxZAwCScuCVzz8AgAdXcNLgXSWcGw7ZpbBpeE7YDQHcrKzQCPEElKriNyDKBHPlfZaBazqHI+w5TgABkVnA7+Sj4gM+LTYCsrhEAAipyEDwABD5ziAiwSOeEidvggjrmAEjMIIMD9oE3pLmaFrIAAHKklafOeS5XoInaBOuCKsP+lYugAjpyzAupI163kg95AeeFRTjOiG6PEUEwXBAmAYhQaRsR5ruMgxiVtOpSVOBfD8PxIAOlArEgNycAACqlJGHayQhuS5EAA)
```sh
--parser typescript
```

**Input:**
```tsx
const StyledH1 = styled.div<StyledComponentProps>`
	font-size: 2.5em;
	font-weight: ${(props) => (props.strong ? 500 : 100)};
	font-family: ${constants.text.displayFont.fontFamily};
	letter-spacing: ${(props) => (props.light ? '0.04em' : 0)};
	color: ${(props) => props.textColor};
	${(props) =>
		props.center
			? ` display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;`
			: ''} @media (max-width: ${(props) => (props.noBreakPoint ? '0' : constants.layout.breakpoint.break1)}px) {
		font-size: 2em;
	}
`;
```

**Output:**
```
Error: Couldn't insert all the expressions
    at transformCssDoc (https://prettier.io/lib/standalone.js:21481:11)
    at Object.embed$4 [as embed] (https://prettier.io/lib/standalone.js:21321:18)
    at Object.printSubtree (https://prettier.io/lib/standalone.js:15712:31)
    at callPluginPrintFunction (https://prettier.io/lib/standalone.js:15829:29)
    at https://prettier.io/lib/standalone.js:15794:16
    at Object.printComments (https://prettier.io/lib/standalone.js:15528:17)
    at printGenerically (https://prettier.io/lib/standalone.js:15793:22)
    at FastPath.call (https://prettier.io/lib/standalone.js:15639:16)
    at printPathNoParens (https://prettier.io/lib/standalone.js:24805:91)
    at Object.genericPrint$3 [as print] (https://prettier.io/lib/standalone.js:23169:28)
```

**Comment by j-f1** [comment]
Also reproduces [with plain JS and no type cast](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlGBPAGzgBMAJARkwF5MNCSA6YgSwDcADAHSk5gDNoMALRpmALzhJMAJgYBWOAFsA3N14DYQgO5xmAcwAWMKQBJgACgAOAJwiW0ASmoA+TFdv2GGW1D2YA-JhyAAzBmFLkoQ4Avqo8-IJCfACGiswEeKbAkFAYybBoDPAAHjBMzGiWBMl4AGKCDBowtanpeLFqMEQw8NYilslgzL5Z7naOLm424wwE+kYBmADkwQzBACxKS+GYwTFxvJAEENaj0-ZOVK7nhSUwAMIQx9Yd8WZjFy6dvDcMYAi9b4wXiBdiYFiVaqZTB8IjFOKYRFI5EozDJOZ6KBCZjwRRoKT-WBwawI1FkxEAKwArhhmHw8EIcvBYASAcTSeTUXchOj9FBWUSSVx4rxeFIlktopgAAKKEjMZJuRTJYraZjEGAGM4eCZXKY6hhQCAAIWscGSAGsAAoQYZYQIrbYE9AwfIwQpQiBUsoAIzNlssttgDD95ot5BilmKTmAQKaInEkhkSgOMGi3HYyhAABoQHYYMx0MhQMlrLYtFbSwg0MgQMlWLbiDmQH7Bha4DBsAMhr5kDBrFS4LmjIoCAB1Aw4uCVQZwbDVnFsHF4WtgNA13PDNDEmBW6zJPTK5ApAjb3MUtDFU1tjvYVJwAAywzgx-RZ5AF+K2GGeiIAEUqQgeBX1PIcQAGaxt2sWsfWSH1CGgZsbDtMd1U1ZAAA5glzaZtzHfdLFrGxp2JVgX1zM0AEcqWYM09wPI8kBPd9tzSPsBzA0RfH-QDgKYt8wNdH1UI1AxkGkXN+2SdIf0eRRGJAI0oHIkAaTgAAVOCa340DomiIA).

**Comment by lydell** [comment]
Actually, [it's better not to specify `parser` like that in your .prettierrc at all](https://prettier.io/docs/en/configuration.html#setting-the-parser-docs-en-optionshtml-parser-option).

**Comment by j-f1** [comment]
I still think we should fix this bug. If

**Comment by inlightmedia** [comment]
There should be a semi-colon before the @media query and after the fat arrow function passing in the prop. This was causing the error. Poorly structured CSS code. The VSCode parser didn't error out though.

```
${(props) =>
		props.center
			? ` display: flex;
                align-items: center;
                justify-content: center;
                text-align: center;`
			: ''} ; <----------- THIS MISSING SEMICOLON WAS CAUSING THE ERROR
                @media (max-width: ${(props) => (props.noBreakPoint ? '0' : constants.layout.breakpoint.break1)}px) {
		font-size: 2em;
	}
```

**Comment by duailibe** [comment]
FTR as of today, [Babel still doesn't parse this (v7.4.5)](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAylAngGwKYBMASBGGBeGaFDAOnQEsA3AHgWPQGEQBbAB3FTCgAUAnEVhAB8AAxEBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.4.5&externalPlugins=)

**Comment by thorn0** [comment]
It [does parse](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAylAngGwKYBMASBGGBeGaFDAOnQEsA3AHgWPQGEQBbAB3FTCgAUAnEVhAB8AAxEBuIA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=typescript&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-syntax-typescript%407.3.3) it if you use `@babel/plugin-syntax-typescript`. Not sure why this plugin isn't included to `@babel/preset-typescript`.

**Comment by Jessidhia** [comment]
As you found, it is more of a problem with the REPL; `@babel/preset-typescript` will only insert the syntax plugin if it thinks the extension is `.tsx` or `.ts`, but the REPL doesn't have it.
