### ISSUE TITLE
No trailing comma for function calls with only a single argument

### ISSUE THREAD

**Issue by calebmer** [prettier/prettier#6304]
This is a formatting request. When I enable `trailingCommas: 'all'` it always bothers me that Prettier adds a trailing comma to a function call with a single item. I think it would look aesthetically better if Prettier did not include a trailing comma _only for function calls with a single argument_. Below are two examples of code I wish didn’t include the trailing comma.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAlgmA6OAPOMAV3gAoAFCAZxyrlUJgEFVVSBKbAdwAs4AnOBWo50AE1wBHUgBYATO068BQyjWwAHIgCMMVPhLjSY-InEXsA3AB0otgIb9+9gJ7YAtvY2l08dwAIAXgA+f184d2xBe1YXACU4GNR4xNiEpJSM9LTU5OzkgBloAHMAWTgYHggxADl7dyFFWxAAGhAIDRh0aCpkUEd+CC5yRwRelHsANwhxVpBtZzAAawqAZQ17MHQoYuQTMzaeGHdUAHUecKoNsDhVsd90Sd8XZHAqXrbtun4YcmdizzIABmMTobQAVlQ8AAhRYrGCrepwArbODA0FwCFQ1bbYoMACKRAg8HRqDBIA2-G+r209m0LlQ0DmGn42xgp3ElWQAA4AAxtFnUOCnZwaV4suDfSZotqSInwP4dcYgexUAC0UDgcDE2rmgjl6EEf3sAPspPJdHc6D2pkxICouIJ8rRSBBZLtMDpHLEXKQcjaJns6AwOwAwhB3ICJqw5kQ6AAVOnjN10AC+qaAA)
```sh
--parser babylon
--trailing-comma all
```

**Input:**
```jsx
client.execute(Post.selectAll().where(Post.id.eq(42)).where(Post.published.eq(true)));

array.map(item => item.reallyReallyReallyReallyReallyReallyReallyReallyLongMethodName());
```

**Output:**
```jsx
client.execute(
  Post.selectAll()
    .where(Post.id.eq(42))
    .where(Post.published.eq(true)),
);

array.map(item =>
  item.reallyReallyReallyReallyReallyReallyReallyReallyLongMethodName(),
);
```

**Desired behavior:**
```jsx
client.execute(
  Post.selectAll()
    .where(Post.id.eq(42))
    .where(Post.published.eq(true))
);

array.map(item =>
  item.reallyReallyReallyReallyReallyReallyReallyReallyLongMethodName()
);
```

**Comment by brainkim** [comment]
Alternatively, maybe the real issue is that fat arrow functions with a concise body (no curly braces)  are split onto multiple lines.

```js
array.map(
  item => item.reallyReallyReallyReallyReallyReallyReallyReallyLongMethodName(),
);
```

doesn’t look bad to me.

**Comment by kaicataldo** [comment]
Do you mind explaining why the number of arguments should matter here? The argument I usually see for enforcing trailing commas is to minimize diff noise, and it feels like doing this would defeat the purpose of using trailing commas at all.

**Comment by lukeed** [comment]
This is fixed in Prettier 2.0; dependent on `--trailing-comma es5` ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAlgmA6OAPOMAV3gAoAFCAZxyrlUJgEFVVSBKbAdwAs4AnOBWo50AE1wBHUgBYATO068BQyjWwAHIgCMMVPhLjSY-InEXsA3AB0otgIb9+9gJ7YAtvY2l08dwAIAXgA+f184d2xBe1YXACU4GNR4xNiEpJSM9LTU5OzkgBloAHMAWTgYHggxADl7dyFFSxAAGhAIDRh0aCpkUEd+CC5yRwRelBiuV1627WcwAGsKgGUNezB0KGLkEzM2nhh3VAB1HnCqNbA4ZbHfdAA3XxdkcCoZkE26fhhyZ2LPZAAMxidDaACsqHgAELzJYwZb1OAFTZwIEguDgyHLTbFBgARSIEHgaNQoJAa34Xxe2ns2norXJ-E2MGO4kqyAAHAAGNoaQZ0Y7ODQvPlwL73VFtSSE+C-DrjED2KgAWigcDgYg1DME0vQgl+9n+9hJZLo7nQO1MGJAVBx+JlqKQu2tMFprLE7KQcjaJns6AwWwAwhB3ACUGKAKwMoh0AAqtPGzra9zMAEkoJrYMswEzOkwM8sYC4GCa4ABfMtAA))

**Comment by lydell** [comment]
@lukeed I think you misunderstood the issue. The request is to use `--trailing-comma all`, but still not get a trailing comma if only one function parameter. With `--trailing-comma es5` you _never_ get trailing function commas.

**Comment by fisker** [comment]
I don't think we can accept this, we print `,` for array and objects

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABAXnQbQDpTroCW8AtlgHwnkB0ATnKgDbMCeASk659+1y359eqaAHMAsnBgALCABMAcqjJxGgkTwAy4qbIXLVACgCUBALoBuAgQzZgBIgDMIEJDTgVM1Up4bCBHkChDWCRXWk5JRU1AOEdKElIgxjTAgBfEAAaEAgABxhiaABnZFBUenoIAHcABQqEUpRUADcIYnlskAAjelQwAGtpAGU8-uJE5Bh6AFc4HJkYMmYAdRlfYrGwOGHG0mIW0jZkcGLSnInitRhavrEyVGQnFiucgCtigA8AIT7BkZiWgmcCeL3mIA+n2GEzEzDgAEUZhB4KDmK8QGN6Fd6CduqhunBmF08vQJjAVh1ZMgABwABhyJIgVxWfTyJxJcGxLRBOQAjkj4Ld8k00MUALRQOBweTSrqMfnERi3VD3R5IZ5o8FXMjEKazLUwuGI5Eg9VgnIwfEU+RUpAAJgtfWIzBhAGEIGQHidBF0ZlcACr4poa9EtOYASSgMtgwzApIKAEEo8MYGw4airul0kA)
```sh
--arrow-parens avoid
--parser babel
--trailing-comma all
```

**Input:**
```jsx
a = [
  item => item.reallyReallyReallyReallyReallyReaongMethodNamereallyReallyLongMethodName()
];

a = {
  foo: item => item.reallyReallyReallyReallyReallyReaongMethodNamereallyReallyLongMethodName()
}
```

**Output:**
```jsx
a = [
  item =>
    item.reallyReallyReallyReallyReallyReaongMethodNamereallyReallyLongMethodName(),
];

a = {
  foo: item =>
    item.reallyReallyReallyReallyReallyReaongMethodNamereallyReallyLongMethodName(),
};

```

**Comment by lydell** [comment]
Agreed, it would be inconsistent with other trailing commas. This has been opened for a long time with only 2 :+1: and 8 :-1: so let’s close it.
