### ISSUE TITLE
MDX parsing error: Unexpected closing tag

### ISSUE THREAD

**Issue by trevordmiller** [prettier/prettier#7041]
According to the [commonmark spec](https://spec.commonmark.org/0.29/#example-136), it seems that the example below is valid markdown. However, Prettier is throwing an error.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZciAA0ICAAcYAS2hNkoAIaFCEAO4AFcwmMpTANwj6smkACNCpsAGs4GFwdP30oAWQYQnw4LQALGABbTgB1eP14JlCwPAdM-WdMgE9kcCZjLXCmMhgbXwEk02RiU04arWYADwAhXwCg3FMkuAAZcLgWto6QbtxwgW4ARXwIeCn2uJBQwhrCMqSsLs8dQnCYVPcYeOQADgAGLVOIGtTfHTLTuD3nSa0AR1W8HqukcIFMTAAtFA4HAcB4tIQ4ID9Ej6qZGs0kK1Nloakl9FEYlsmAtlkDJtjplsYKYvJcsNdkAAmLTRUz6TgLTBJJplKDQP4gfA1AAqdMcOJqAF9pUA)
```sh
--parser mdx
```

**Input:**
````mdx
<CodeSurfer>

```js
console.log(1);
```

</CodeSurfer>
````

**Output:**
````mdx
SyntaxError: Unexpected closing tag "CodeSurfer". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:1)
> 1 | <CodeSurfer>
    | ^
  2 | 
  3 | ```js
  4 | console.log(1);
````

**Expected behavior:**

If this is valid MDX it should parse it and format it without an error.

**Comment by thorn0** [comment]
What did the **MDX** spec say about this?

**Comment by karlhorky** [comment]
Hm, there is no mention of it from my quick glance at https://github.com/mdx-js/specification, but in the issues there is https://github.com/mdx-js/specification/issues/11, which mentions:

**Question:**
> Is it possible to nest markdown within a JSX tag?

**Answer:**
> This will work if you add newlines between the JSX and Markdown tags
>
> ```jsx
> <Reference title='JS Reference'>
> 
> My explanation of `this` 
> 
> </Reference>
> ```

It seems that in Prettier, this example [does not work](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeASnAZnATgsOAAhgEsYAbOAXgHIApAZSMx3ykNoD4AdKPgLIBPInAAeABwoBDKNLLQiELEQAGMABakAzqqJ8+qAPSs8BOFxAAaEBAkKo25KGm5cEAO4AFVwicppADcIUgATaxAAI1xpMABrOBhGCVjSKABzZBhcAFc4Gw0YAFsKAHUteG0UwkY-clJA8iFkcG0nGzTtPBgvGPSi6WQsaQoumwArbTEAIRj4xMZpIrgAGTS4IZGxkEmxRjT0qgBFHIh4TdH8kBTcLtwWotCxCIlcNJhSsM1kAA4ABhsrwgXVKMQkLVecDugQ2NgAjqd4L07P4QNJtABaKBwOChXERfAI0j4XrSfqDJDDS42LpFUhZXJXbQHY6IjaUrZXGDSSKfULfJAAJhs2WkpAoBwAwhAigMWlBoLCQDkugAVHn+KnbQJ5ACSUDxsEYYDe9gAggbGDAhFQLl0AL72oA).

Furthermore, it seems as if nesting other Markdown after newlines generally [does not work](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UhAyhALZwAEABpOnNYYagPRZ4gA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODGK99mKAHNkMCQFc43ABYwyAGwDqTzPCFmwcMRKPjg+AJ7I4EIi3BZCcBIwcnqWZGLIAGZibvHcAFZCAB4AQnqGxsRiFAAyFnCZ2bkgBYXEFpZucACKdhDwDTmOIGYS8RKRZOiFWrwSFjAeGjBOyAAcAAzcsxDxHnq8kbNwY9j13ACOvfDJfMogYkIAtFBwcPSa3BJwl5hfyWKpdJILKDbjxMiYGz2IZCdqdHp9erAxpDGBibSLdDLZAAJm4tjEmDc7QAwuQ0pEoNAziA7PEACro5QgprYBwASSg9FgxDAc34AEEucQYGFOgN4gBfSVAA):

```markdown
<div>

Some `code`

</div>
```

**Error:**

```
SyntaxError: Unexpected closing tag "div". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:1)
> 1 | <div>
    | ^
  2 | 
  3 | Some `code`
  4 | 
```

This [does work](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UhAyhALZwAEABpOnNYYagPRZ4gA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODGK99mKAHNkMCQFc43ABYwyAGwDqTzPCFmwcMRKPjg+AJ7I4EIi3BZCcBIwcnqWZGLIAGZibvHcAFZCAB4AQnqGxsRiFAAyFnCZ2bkgBYXEFpZucACKdhDwDTmOIGYS8RKRaRIG6LJQWrwSFjAeGjBOyAAcAAzcCxDxHnq8kQtwY9j13ACOvfDJfMogYkIAtFBwcPSa3BJwN5i-ZJiVLpJBZQbceJkTA2exDITtTo9Pr1MGNIYwMTaFboNbIABM3FsYkwbnaAGFyGlIlBoJcQHZ4gAVLHKcFNbAOACSUHosGIYEW-AAgrziDAwp0BvEAL4yoA) using the `markdown` parser.

**Comment by karlhorky** [comment]
Another mention of it in https://github.com/mdx-js/mdx/issues/628 (admittedly, an RFC):

> ```jsx
> <Note>
> 
> This *is* **markdown**!
> 
> </Note>
> ```

> **Motivation:**
> This approach is currently being used in the wild and in production.

**Comment by karlhorky** [comment]
cc @pomber maybe worth following along here, since your library is relying upon this approach.

**Comment by karlhorky** [comment]
One last link: in [the **Try it** editor](https://mdxjs.com/#try-it) on the official MDX website, both of the examples work - both the example with the `div` and the original example with the `CodeSurfer` component.

**Comment by thorn0** [comment]
The MDX support in Prettier is really basic. Prettier parses MSX like plain Markdown with the only (I guess) difference that if a JSX block is found, it's passed to Babel. That's it. Things like inline JSX and Markdown inside JSX blocks aren't supported as of now.

**Comment by karlhorky** [comment]
> Prettier parses MDX like plain Markdown

Hm, but the original example actually works with the `markdown` parser:

[Markdown (no errors)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZciAA0ICAAcYAS2hNkoAIaFCEAO4AFcwmMpTANwj6smkACNCpsAGs4GFwdP30oAWQYQnw4LQALGABbTgB1eP14JlCwPAdM-WdMgE9kcCZjLXCmMhgbXwEk02RiU04arWYADwAhXwCg3FMkuAAZcLgWto6QbtxwgW4ARXwIeCn2uJBQwhrCMqbCfyxrKE8dQnCYVPcYeOQADgAGLQuIGtTfHTKLuD3nSZaACOq3g9V0jhApiYAFooHA4DgPFpCHAQfpUfVTI1mkhWpstDUkvoojEtkwFstQZM8dMtjBTF4blg7sgAExaaKmfScBaYJJNMpQaCAkD4GoAFUZjnxM2csQAklAcLBcGBLnoAILK3AwYrcDY1AC+RqAA)

It also isn't true for the `div` MDX <> Markdown comparison that I posted:

[MDX (fails)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UhAyhALZwAEABpOnNYYagPRZ4gA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODGK99mKAHNkMCQFc43ABYwyAGwDqTzPCFmwcMRKPjg+AJ7I4EIi3BZCcBIwcnqWZGLIAGZibvHcAFZCAB4AQnqGxsRiFAAyFnCZ2bkgBYXEFpZucACKdhDwDTmOIGYS8RKRZOiFWrwSFjAeGjBOyAAcAAzcsxDxHnq8kbNwY9j13ACOvfDJfMogYkIAtFBwcPSa3BJwl5hfyWKpdJILKDbjxMiYGz2IZCdqdHp9erAxpDGBibSLdDLZAAJm4tjEmDc7QAwuQ0pEoNAziA7PEACro5QgprYBwASSg9FgxDAc34AEEucQYGFOgN4gBfSVAA)

[Markdown (no errors)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UhAyhALZwAEABpOnNYYagPRZ4gA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODGK99mKAHNkMCQFc43ABYwyAGwDqTzPCFmwcMRKPjg+AJ7I4EIi3BZCcBIwcnqWZGLIAGZibvHcAFZCAB4AQnqGxsRiFAAyFnCZ2bkgBYXEFpZucACKdhDwDTmOIGYS8RKRaRIG6LJQWrwSFjAeGjBOyAAcAAzcCxDxHnq8kQtwY9j13ACOvfDJfMogYkIAtFBwcPSa3BJwN5i-ZJiVLpJBZQbceJkTA2exDITtTo9Pr1MGNIYwMTaFboNbIABM3FsYkwbnaAGFyGlIlBoJcQHZ4gAVLHKcFNbAOACSUHosGIYEW-AAgrziDAwp0BvEAL4yoA)

If this case was handled the same as the `markdown` parser (newlines inside tags), maybe this issue would be fixed.

**Comment by karlhorky** [comment]
Ah, in my comment above I missed your point about "if a JSX block is found, it's passed to Babel"... maybe that's the reason describing this inconsistency?

**Comment by pomber** [comment]
I think it used to work, at least inside of VS Code. Are there playgrounds for older versions of Prettier?

**Comment by thorn0** [comment]
@pomber Depends on what you call "to work". It might _kind of_ work again in the next version because of https://github.com/prettier/prettier/pull/6949. The `SyntaxError` should get fixed, but Prettier won't really format JSX blocks with Markdown inside. It'll just leave them as is like it currently does with inline JSX. So if someone here is blocked by this issue, consider installing Prettier directly from GitHub (`npm install prettier/prettier`) until this fix is released.

To my knowledge, there is no playgrounds for older versions.

**Comment by pomber** [comment]
Yes, maybe it was just ignoring the JSX's children. That was good enough for me.  

BTW, I tried 6949 [playground](https://deploy-preview-6949--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZKjQ0gANCAgAHGAEtoTZKACGhQhADuABUsJTKcwDcIhrNpAAjQubAAazgYXD0AwygBZBhCfDgdAAsYAFtOAHVEw3gmcLA8J2zDV2yAT2RwJlMdSKYyGDt-ARTzZGJzTjqdZgAPACF-IJDccxS4ABlIuDaOrpBe3EiBbgBFfAh4Gc6EkHDCOsIKlKwe7z1CSJh0zxhE5AAOAAYdc4g69P89CvO4A9dpnQAR3W8Ea+mcIHMTAAtFA4HAcF4dIQ4MDDCjGuZmq0kO1tjo6ilDDE4jsmEtViDprjZjsYOYfNcsLdkAAmHSxcyGThLTApFoVKDQAEgfB1AAqDOceLmrniAEkoDhYLgwBcDABBJW4GClbhbOoAX0NQA) and it's still throwing a similar error.

**Comment by thorn0** [comment]
It's a different error though. It happens only on the playground.

**Comment by Tielem** [comment]
Subscribing to this issue, since I believe I am running into this as well.

I am creating a Gatsby + MDX template. ESLint and Prettier fail with `SyntaxError: Unexpected closing tag "div"` ; similar to above. However, building or transpiling works as intended.

I can provide a reference to the project soon.

**Comment by karlhorky** [comment]
Ah, just ran into this again with an existing project, which I believe wasn't erroring out before.

Now any files in the project using the pattern below are not formatted by the Prettier VS Code extension anymore.

Here's an example (using [gatsby-remark-embedded-codesandbox](https://github.com/elboman/gatsby-remark-embedded-codesandbox):

```html
<details>
  <summary>Solution</summary>

[Solution on CodeSandbox](codesandbox-link://exercises/002-solution/)

</details>
```

**Comment by arayaryoma** [comment]
It seems have fixed by #6949

**Comment by karlhorky** [comment]
Hm, not sure about that. It just throws a different error ("SyntaxError: Unexpected token"):

```
SyntaxError: Unexpected token (2:34)
  1 | <$><details>
> 2 |   <summary>Solution</summary></$>
    |                                  ^
```

[#6949 Playground](https://deploy-preview-6949--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJnGBDAlgGwGcA+AHSgAILVCBXAW3uwCcBPYgZQn1pl2lQB6Ooxbty5ANpcefaBXkBhCJg7Yo6AEYQAHgF0AFJEyF1W3QFp8uKAGskgwXB1xmYXITiFBABh8AmC0JuXn4oQQBKCSghTBwCEhAAGhAIAAc5KEJkUBZmCAB3AAUWBGyUbAA3CFx0ZJBNZmwwWywONOabAHNkGGZaOBSACxh6fAB1Idx4Qg6wOA4y6dxK6dZkcEJslJtPZhgipq6mZAAzbCJBkAArQh0AISaWtux6OAAZGzgzi88U250HG6+DgAEVaBB4D9LikOsw9ht6OgdPU0swbDBxrUYENkAAOHyw-KecZNNIbNFeVyVb4pACOEPgh3S5RA2EIFigcDgmDqKWYcAZuAFh2wx2w0L+IE89FwvX6V0IwLBjO+SHOMJAOE0WPQOOQ-hSfTw1igXWUog2UGgtJAtE8ABVsJpyhqpZUBgBJDQIGAcMDojIAQQ0HBgrBBkrgAF9o0A)

**Comment by cpboyd** [comment]
It seems like there's an issue with using `style={{}}` on a multi-line tag:

```jsx
---
title: Contact
---

import { Button } from '@rmwc/button';

# Contact

<Button
  raised
  style={{ margin: '8px' }}
>
  Message Me
</Button>
```

I'm getting this:
error  Parsing error: Unexpected closing tag "Button". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags

**Comment by JounQin** [comment]
@cpboyd Please try `yarn add -D prettier@prettier/prettier`

**Comment by JounQin** [comment]
@karlhorky That seems to be a different regression, and we can not simply consider all contents in `jsx` as `jsx`...

**Comment by karlhorky** [comment]
> That seems to be a different regression, and we can not simply consider all contents in jsx as jsx... Can you open a specific issue to track it?

@JounQin sure, definitely. Which comment of mine are you referring to? The one about the `summary` and `details` with Markdown inside (the one that throws "SyntaxError: Unexpected token")?

I guess because it's a different issue, we will leave @trevordmiller's #7041 open too?

**Comment by JounQin** [comment]
@kachkaev Yeap, https://github.com/prettier/prettier/issues/7041#issuecomment-568284711

> I guess because it's a different issue, we will leave @trevordmiller's #7041 open too?
Sure, although it has been fixed actually. 🤣

**Comment by karlhorky** [comment]
> Sure, although it has been fixed actually. rofl

Where has this been fixed? In an unreleased version of Prettier?

Because the original Playground link still fails:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZciAA0ICAAcYAS2hNkoAIaFCEAO4AFcwmMpTANwj6smkACNCpsAGs4GFwdP30oAWQYQnw4LQALGABbTgB1eP14JlCwPAdM-WdMgE9kcCZjLXCmMhgbXwEk02RiU04arWYADwAhXwCg3FMkuAAZcLgWto6QbtxwgW4ARXwIeCn2uJBQwhrCMqSsLs8dQnCYVPcYeOQADgAGLVOIGtTfHTLTuD3nSa0AR1W8HqukcIFMTAAtFA4HAcB4tIQ4ID9Ej6qZGs0kK1Nloakl9FEYlsmAtlkDJtjplsYKYvJcsNdkAAmLTRUz6TgLTBJJplKDQP4gfA1AAqdMcOJqAF9pUA

**Comment by karlhorky** [comment]
> We need help from @mdx-js team.

This sounds reasonable. Wonder if @johno, @silvenon or @wooorm could help here...

**Comment by JounQin** [comment]
@karlhorky Sorry I was confused this issue with #7176, your issue is same as this one: Markdown content inside `jsx` block with blank lines.

**Comment by wooorm** [comment]
What is the question? If it is whether the following is valid MDX, then yes, it is.

~~~md
<CodeSurfer>

```js
console.log(1);
```

</CodeSurfer>
~~~

**Comment by JounQin** [comment]
@wooorm We're asking help for sharing ideas about maintaining `mdx` support in `prettier`.

**Comment by karlhorky** [comment]
> > Sure, although it has been fixed actually. 🤣
> Where has this been fixed? In an unreleased version of Prettier?

Ah actually, thanks to @kachkaev's comment on #7176 (https://github.com/prettier/prettier/issues/7176#issuecomment-571218217), I just tried adding `"prettier": "prettier/prettier"` to my `devDependencies` and it seems to format with all examples here! 🚀

![Kapture 2020-01-27 at 11 23 34](https://user-images.githubusercontent.com/1935696/73167119-8e7edd00-40f7-11ea-993d-81d20cf97450.gif)

So it looks like this will be fixed as soon as Prettier `1.20.0` or `1.19.2` is released. 🙌

**Workaround for now:**

Change your version of Prettier in your package.json to `"prettier": "prettier/prettier"`. If you're using VS Code, this new local version will be picked up automatically by `prettier-vscode`.

**Comment by trevordmiller** [comment]
Any updates on when this might be released? Thank you!

**Comment by karlhorky** [comment]
Seems like this change that worked with the Prettier master branch before `prettier@2.0` is not a part of the v2 release :(

![Screen Shot 2020-04-09 at 21 00 54](https://user-images.githubusercontent.com/1935696/78931031-7804e280-7aa5-11ea-97a1-327bc7501406.png)

[Playground](https://deploy-preview-7417--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAwhAJnAygVwCcAzOQgPgB0pqADegKwGdrIomIAbOAOk4gDmACgCMASgDcdetWqoA9JhwESZciAA0ICAAcYAS2hNkoAIaFCEAO4AFcwmMpTnK6YCexrQCNCpsAGs4GFwdP30oAWQYQnw4LQALGABbTgB1eP14JlCwPAdM-QA3TLdkcCZPEHCmMhgbXwEk02RiZxqtZgAPACFfAKDcUyS4ABlwuBa2uJAu3HCBbgBFfAh4Sc52kFDCGsIypKxOzS3CcJhU-SwYeOQADgAGLR1LGtTfHTLnuF3Cia0ARxW8HqukcIFMTAAtFA4HAcFhjoQ4ID9Ej6qZGs0kK0NtMakl9FEYnj5ksgRNsVMtDBTF4LlcbkgAEzU3z6TjzTBJJplb4AVmO+BqABVaY4cZtCrEAJJQHCwXBgU56ACCctwMDc3HWNQAvrqgA) (playground based on #7417)

![Screen Shot 2020-04-09 at 21 00 27](https://user-images.githubusercontent.com/1935696/78931039-7cc99680-7aa5-11ea-8820-238fb2ae66d5.png)

[Playground](https://deploy-preview-7417--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAJnGBDAlgGwGcA+AHSgAILVCBXAW3uwCcBPYgZQn1pl2lQB6Ooxbty5ANpcefaBXkBhCJg7Yo6AEYQAHgF0AFJEyF1W3QFp8uKAGskgwXB1xmYXITiFBABh8AmC0JuXn4oQQBKCSghTBwCEmiQABoQCAAHOShCZFAWZggAdwAFFgQclGx8QuxWHNTNZmwwWywOdOabAHNkGGZaOFSACxh6fAB1Idx4Qg6wOA5y6dwAN2nWZHBCepAbT2YYYqaupmQAMyrPVIArQh0AISaWtux6OAAZGzhzy8GQW50HG6+DgAEVaBB4D8iH8Osx9pt6OgdCkQOlmDYYONcOgYENkAAOHypdEQTzjJrpTboryuFbfVIARwh8COGQqIGwhAsUDgcEw6FRzDgzNwwqO2BO2GhVxAnnouF6-T+hGBYJZ3yQFxhqRwmmxuPxSH8uqaBG6ylEmy8AFZUbRPAAVbCaCra2UrAYASQ0CBgHDAGMyAEENBwYKwQTK4ABfGNAA) (playground based on #7417)

**Comment by bsgreenb** [comment]
This issue has been solved for me via `npm i -D prettier@latest`

**Comment by thorn0** [comment]
@bsgreenb It might seem that it works sometime, but this never was implemented.

In this code
````
<CodeSurfer>

```js
console.log(1);
```

</CodeSurfer>
````
the tags aren't parsed as JSX at all. Prettier just leaves them as is, without formatting.

Whereas in this code
````
<CodeSurfer>
```js
console.log(1);
```
</CodeSurfer>
````
Prettier can parse the tags as JSX, but it doesn't parse the text inside as Markdown.

**Comment by Kosai106** [comment]
I just encountered the same issue. Oddly enough, using `--require-pragma` seems to make the error go away, at least on the Prettier Playground.

That said, I updated Prettier in my repo and that seems to have worked as well in my case.

**Comment by karlhorky** [comment]
@Kosai106 `--require-pragma` will ignore all files without a pragma at the top of the file. MDX pragma:

```md
<!-- @prettier -->
```

So it was just disabling Prettier for that file. If you try with `--require-pragma` and the pragma above, you'll have the same errors again.

Ref: https://prettier.io/docs/en/options.html#require-pragma

**Comment by Kosai106** [comment]
@karlhorky Ah, yeah that would explain it, lol. It was pretty late, I didn't think too much about it.

Like I said however, upgrading the Prettier version seems to have solved the issue on my end.

**Comment by kachkaev** [comment]
MDX v2 is out:

- https://github.com/mdx-js/mdx/releases/tag/2.0.0
- https://mdxjs.com/blog/v2/

The example attached to this issue may become pretty common soon 🤔
