### ISSUE TITLE
Css variable in styled-components breaks because of the extra space in a template string.

### ISSUE THREAD

**Issue by shermendev** [prettier/prettier#7207]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AA0iwgCckACEgQ2oAoBaNgEmEpoF8AlAG4yIADQgIABxhFoqZKGbUIAdwAKzBApSMSEIrnEgARtUZgA1nBgBlKRaJQA5shjUArnAkALGAFssAHUfInhUBzA4W20w0jCMZHBUBQknVDhqGHVzZ39GZAAzRiwMiQArVAAPACFzKxtbRn84ABknOCKSspBKqtsnZxwARQ8IeC7S7xAHagzqJJNGEzgsYylqJxggwxgfZAAOAAYJDYgMoPMpJI24eZJOiQBHMfgc6R0QRlQ2KDg8PDGahwF5EYE5Rh5ApIYpTCQZfxENyeaaoQYjV6dGHdaYwZY7XB7ZAAJgk7kYRCwgwAwhB-PkklBoI8QB4MgAVZY6WE9EheACSUFwCDsYE2MgAgkLbJgcJMMnw+EA)
```sh
--parser babel
```

**Input:**
```jsx
styled.div`color: var(--${color});`
```

**Output:**
```jsx
styled.div`
  color: var(-- ${color});
`;

```

**Expected behavior:**
`var(--${color})` to be without a space after -- as it breaks the css.

Any way to work around or disable it?

**Comment by fisker** [comment]
#6794 should be able to fix this

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7883

**Comment by glandre** [comment]
Hi @thorn0 and @fisker, I am currently using 2.0.5 and this still happens...
What are the steps to fix this behaviour?

**Comment by thorn0** [comment]
@glandre The bug reported in this issue has been fixed. I'm not able to reproduce it with 2.0.5. If you can reproduce your problem on the [Playground](https://prettier.io/playground), please use the <kbd>Report issue</kbd> button there to open a new bug report.

**Comment by glandre** [comment]
@thorn0, thank you for your reply. Maybe there's something else in my configuration that is getting in the way...

One point to notice is that I'm using TypeScript.

Take a look at this Codesandbox: https://codesandbox.io/s/elastic-colden-kvyzm?file=/src/App.tsx
It has prettier by default.

Notice the extra space after `-radius-`

Let me know if it's just some missing configuration, or if I should go ahead and open a new issue.

Thank you again for your help.

**Comment by thorn0** [comment]
@glandre That's a different bug, fixed by #8255 but not yet released.

**Comment by glandre** [comment]
Great!
When is the next release to be expected?
thank you @thorn0!
