### ISSUE TITLE
Mangling of Sass Custom Properties or CSS variables

### ISSUE THREAD

**Issue by robert-j-webb** [prettier/prettier#8604]
As a refresher, [here's what custom properties are](https://sass-lang.com/documentation/style-rules/declarations#custom-properties)

Their syntax is very permissive:

> CSS custom properties, also known as CSS variables, have an unusual declaration syntax: they allow almost any text at all in their declaration values. What’s more, those values are accessible to JavaScript, so any value might potentially be relevant to the user. 

Which means it's really easy to mangle them. I found 2 ways.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0RAhkQG5yoCeRANtAOZFgDOblpqAlqQEb04RKKQC2wmAAtSMImNJ0A7j3r15pANbDy9HlGH9UcLUiwBiYABIK3PoLjEst3gKFEATADobdt8IBmLAAqLA8AXwBufEIY4jJWDi5XByJpWSI2KQgAV3oAEyJtOAAHIh4YTjY4MR5IRigzPAJCLHqIVDNjfLio-HCQABoQCBKYHmg2ZFBudCUABW4EKZRSeiVFKeGjUjBtGABlEt39JmQYVBy4YakYMXoAdSkKuDZjsDgD5YqeCgqaZDgDhDED6aqoGDzVCkJgKZAAMzW1WGACs2AAPABC0L2cEO4jgABl9HAEUjriA0eiDqchABFHKYUlIRH0ZEgY6ocGAtjsLYc3iwB48fLSZAADgADMMSuhqg9oSVAbLXtQqCCAI6M+BQ0YrECkTgGOD5E0g4xanjGKEwuEs8nDaq1c6XClsWlwBlMslsikwATC0VSZAeYYXUiqU4AYQgYjtIFeAFYQTlqgAVAQrVnsihXACSUFNsAOYF4YwAgoWDjAaEIfdVwuEgA)

**Input:**

```scss
:root {
  --a-very-long-css-variable-name-that-may-will-make-a-line-break: #{$variable - variable-2.$variable-3 * 2};
  
  --a-css-variable-that-should-keep-its-semicolon: {
    color: red
  };
}
```

**Output:**

```scss
:root {
  --a-very-long-css-variable-name-that-may-will-make-a-line-break: #{$variable -
    variable-2.$variable-3 * 2};

  --a-css-variable-that-should-keep-its-semicolon: {
    color: red;
  }
}
```

**Expected behavior:**

The semicolon should be kept and whitespace should not be added or removed.

We can not modify anything inside of the variable declaration, or we may mangle it. These values must be past directly to the user.

**Comment by nex3** [comment]
For more context, the value of a custom property is syntactically [specified as](https://www.w3.org/TR/css-variables-1/) a [`<declaration-value>`](https://www.w3.org/TR/css-syntax-3/#typedef-declaration-value):

> The `<declaration-value>` production matches any sequence of one or more tokens, so long as the sequence does not contain `<bad-string-token>`, `<bad-url-token>`, unmatched `<)-token>`, `<]-token>`, or `<}-token>`, or top-level `<semicolon-token>` tokens or `<delim-token>` tokens with a value of "!". It represents the entirety of what a valid declaration can have as its value.

What's more, the value is made available to JavaScript, so changing *any* token in any way will change the runtime semantics of the CSS/Sass file. The block-like syntax used in @robert-j-webb's second example is actually used by Polymer, for example.

The only exception in standard CSS is whitespace: the value made available to JavaScript is reconstructed from the token stream, so JS only sees a single space in place of any whitespace in the source document. This means it's safe to change whitespace as long as no new whitespace is added between two tokens that didn't have it yet, and all tokens that were originally separated by whitespace are still separated by at least one space, newline, or tab.

There's also an exception in Sass in particular: if a custom property value contains `#{`, Sass interprets it as Sass-style interpolation. It's safe to do normal expression-level formatting on anything inside that interpolation, as long as whatever's outside of it remains untouched. For that reason and the whitespace exception, I think @robert-j-webb's first example is actually a valid transformation.

**Comment by ModulesUnraveled** [comment]
I thought I'd chime in here with an issue I found:
```
  --color-button-primary: var(--color-theme-button-primary, var(--color-blue-brand));
  --color-button-secondary: var(--color-theme-button-secondary, var(--color-basics-white));
  --color-blockquote-accent: var(--color-theme-blockquote-accent, var(--color-blue-brand));
```
gets converted to
```
  --color-button-primary: var(
    --color-theme-button-primary,
    var(--color-blue-brand)
  );
  --color-button-secondary: var(
    --color-theme-button-secondary,
    var(--color-basics-white)
  );
  --color-blockquote-accent: var(
    --color-theme-blockquote-accent,
    var(--color-blue-brand)
  );
```
which creates invalid css custom properties because of the unexpected spaces. (the fallbacks are never considered).

I can add ignores:
```
  /* prettier-ignore */
  --color-button-primary: var(--color-theme-button-primary, var(--color-blue-brand));
  /* prettier-ignore */
  --color-button-secondary: var(--color-theme-button-secondary, var(--color-basics-white));
  /* prettier-ignore */
  --color-blockquote-accent: var(--color-theme-blockquote-accent, var(--color-blue-brand));
```

But that's tedious... Or ignore the whole file, but I'd really just like to disable the printwidth for this file, or have Prettier know more about css custom properties so that it doesn't break lines unexpectedly.

**Comment by alexander-akait** [comment]
Yes, we should output custom variables as is, because any tokens can be inside, but in your example should be fine, can you provide example?

**Comment by ModulesUnraveled** [comment]
Ah, you know what? It actually was working, it just didn't look like it in Chrome dev tools...

Here's what I saw in the dev tools. You'll notice:
1. `color: var(--color-blockquote-accent);` is grayed out, as though it has not been defined.
2. `--color-blockquote-accent` appears to be using `--color-theme-blockquote-accent` (but that is actually undefined)
3. The fallback of `--color-blue-yale` appears to be disregarded... when actually, that's the color that is being applied.

![Screen Shot 2022-02-08 at 9 16 04 AM](https://user-images.githubusercontent.com/1663810/153017105-f8429eb8-fb17-4555-98d5-48016d19f962.png)

When I click into the value in dev tools, I see the formatting is consistent with prettier's result.
![Screen Shot 2022-02-08 at 9 16 17 AM](https://user-images.githubusercontent.com/1663810/153017106-7f9aeb11-91cd-4399-9cf4-05246b6fda70.png)

If I add the `// pretier-ignore` lines like i mentioned in my last comment, I get the expected view in dev tools:
1. `color: var(--color-blockquote-accent);` is blue, and I can click on it to be taken to the definition below.
2. `--color-blockquote-accent` is acknowledging that `--color-theme-blockquote-accent` is undefined
3. The fallback of `--color-blue-yale` is properly highlighted as the color in use

![Screen Shot 2022-02-08 at 9 16 32 AM](https://user-images.githubusercontent.com/1663810/153017108-12d12abb-5190-4c31-bd03-058ebc736c9a.png)

So, my issue may actually be with dev tools, since it is technically working with the extra spaces and line breaks, but they are reporting it as not working... unless the fact that it's working is a side-effect of their renderer... maybe it doesn't work in other browsers? I'll have to check on that.

**Comment by ModulesUnraveled** [comment]
Yeah, I just checked, and it works in both Safari and Firefox as well.

Safari's dev tools are less than helpful. They show the formatted string, and don't have any indications about what's being used. (But the browser is rendering the correct styles)

![Screen Shot 2022-02-08 at 9 38 28 AM](https://user-images.githubusercontent.com/1663810/153021756-5aa6c85f-99fe-4a2f-b517-fe37a00648a0.png)

But Firefox shows everything as expected. There are some extra spaces in it, but it's properly highlighting the values that are being applied properly.
![Screen Shot 2022-02-08 at 9 38 57 AM](https://user-images.githubusercontent.com/1663810/153021802-39074084-2d56-44e9-98d5-92ee77cd481f.png)

Sorry that this isn't actually a prettier issue (for me) but a browser dev tools thing.

I think I'll still ignore the lines though, since it enhances the development experience (particularly for debugging, now, and later)

**Comment by nex3** [comment]
It looks like the original issue is [fixed in Prettier 3.0.0](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0RAhkQG5yoCeRANtAOZFgDOblpqAlqQEb04RKKQC2wmAAtSMImNJ0A7j3r15pANbDy9HlGH9UcLUiwBiYABIK3PoLjF8hQrd4ChRAEwA6G3Y9hAGYsACosLwBfAG58Z2IyVg4udwciaVkiNikIAFd6ABMibTgAByIeGE42ODEeSEYoMzwCFwaIVDNjAtjWmPxIkAAaEAhSmB5oNmRQbnQlAAVuBGmUUnolRWmRo1IwbRgAZXE4ABl9OGQAM3WandQ9g8PSvf0mZBhUXLgRmrqPr4-EBsN5CACKuUwlyQN3odxAACs2AAPQ6guAQqHXW5AgCOkPgC3QpVWIFInAMcAKVOGIE+pFUbwAwhAxApkGS1LSQVAmEIAIIwT48fi5QnUc4GbFwoFSGBiegAdSklTgbBeYDghxWlR4FEqNA57G2IAo3wAklBqbBDmBeON+VbDjAaEJpfDSugaoqHqUOZ61dQqLT9DVUDAiaQmOyYTiRi9UGGOWxjbTPfoYIqeAVpMgABwABhGxnxPGMkejpHdQJgAizOakyC8I1yNQAKgJVrD4bV+FTqQVTqRebko3AAGIdBRCt4c0hiiAgSKRIA), so this can be closed out.

**Comment by artemkovalyov** [comment]
This is still broken for me when `var( )` function is used:
Take this input:

```css
 --md-sys-color-on-primary-container: var(--md-sys-color-on-primary-container-light);
  --md-sys-color-on-primary-container-high-contrast: var(--md-sys-color-on-primary-container-hight-contrast-light);
```

is converted into a declaration with line breaks which is as of now incorrect and not picked up by the latest Chrome:

```css
--md-sys-color-on-primary-container: var(--md-sys-color-on-primary-container-light);
--md-sys-color-on-primary-container-high-contrast: var(
--md-sys-color-on-primary-container-hight-contrast-light
);
```

I used the latest prettier from the command line to test this out. My code editor has the same issue:

```bash
± |main U:12 ?:2 ✗| → npx prettier -v
3.0.1
```

**Comment by artemkovalyov** [comment]
Prettier ignore is still the only workaround:

```css
--md-sys-color-on-primary-container: var(--md-sys-color-on-primary-container-light);
/* prettier-ignore */
--md-sys-color-on-primary-container-high-contrast: var(--md-sys-color-on-primary-container-hight-contrast-light);
```

**Comment by nex3** [comment]
Adding whitespace _within `var()` specifically_ is valid, because `var()`s are resolved before the computed value of the property is readable by JavaScript. That said, the same issue reproduces with other function names, which is not valid.

**Comment by Ugoku** [comment]
This is also a problem in the following example:

```css
body:has( .foo) {}
```

Gets changed to 
```css
body:has(.foo) {}
```

which means something completely different! Using `/* prettier-ignore */` works, but is not ideal.
